apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: orders
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: orders
data:
  init.sql: |
    CREATE TABLE orders (
      id INT AUTO_INCREMENT PRIMARY KEY,
      type VARCHAR(255) NOT NULL
    );
    INSERT INTO orders (type) VALUES ('doohickey');
    INSERT INTO orders (type) VALUES ('thingamabob');
    INSERT INTO orders (type) VALUES ('flimflam');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: orders
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "false"
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: orders
        - name: MYSQL_USER
          value: orders
        - name: MYSQL_PASSWORD
          value: orders
        - name: MYSQL_ROOT_PASSWORD
          value: orders
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
      - name: mysql-initdb
        configMap:
          name: mysql-initdb