apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-otel-collector-deployment
  namespace: orders
  labels:
    app: dynatrace-otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynatrace-otel-collector
  template:
    metadata:
      labels:
        app: dynatrace-otel-collector
    spec:
      serviceAccountName: otelcontribcol
      containers:
      - name: dynatrace-otel-collector
        image: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest
        args: ["--config=/etc/otel/collector/collector.yaml"]
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 8888
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DT_API_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace-otelcol-dt-api-credentials
              key: DT_API_ENDPOINT
        - name: DT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-otelcol-dt-api-credentials
              key: DT_API_TOKEN
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otel/collector
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: dynatrace-otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-otel-collector-service
  namespace: orders
spec:
  selector:
    app: dynatrace-otel-collector
  ports:
  - name: grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: http
    protocol: TCP
    port: 4318
    targetPort: 4318
  - name: health
    protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP
