apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: dynatrace-collector
  namespace: orders
spec:
  mode: "daemonset"
  image: "ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest"
  resources:
    limits:
      memory: 512Mi
  env:  # Define environment variables here
    - name: DT_API_ENDPOINT  # Environment variable name
      valueFrom:
        secretKeyRef:
          name: dynatrace-otelcol-dt-api-credentials  # Secret name
          key: DT_API_ENDPOINT  # Key in the secret
    - name: DT_API_TOKEN  # Environment variable name
      valueFrom:
        secretKeyRef:
          name: dynatrace-otelcol-dt-api-credentials  # Secret name
          key: DT_API_TOKEN  # Key in the secret
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      otlphttp:
        endpoint: "${DT_API_ENDPOINT}/api/v2/otlp/v1/traces"
        headers:
          Authorization: "Api-Token ${DT_API_TOKEN}"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
